services:
  api:
    build:
      context: /srv/apps/beelder/staging/core
      dockerfile: Dockerfile
    container_name: beelder-api
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - beelder-network

  app:
    build:
      context: /srv/apps/beelder/staging/app
      dockerfile: Dockerfile
    container_name: beelder-app
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - beelder-network
    depends_on:
      - api

networks:
  beelder-network:
    driver: bridge