services:
  api:
    build:
      context: /srv/apps/beelder/production/core
      dockerfile: Dockerfile
    image: beelder-api:latest
    container_name: beelder-api
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - beelder-network
      - infra-network
    environment:
      - SERVER_COMMANDS_TOPIC=beelder.server.commands
      - SERVER_PROGRESS_TOPIC=beelder.server.progress
      - GROUP_ID=beelder.api.group
      - BROKER=redpanda:9092

  app:
    build:
      context: /srv/apps/beelder/production/app
      dockerfile: Dockerfile
    image: beelder-app:latest
    container_name: beelder-app
    ports:
      - "82:80"
    restart: unless-stopped
    networks:
      - beelder-network
    depends_on:
      - api

networks:
  beelder-network:
    driver: bridge
  infra-network:
    name: infra-network
    external: true