services:
  api:
    build:
      context: /srv/apps/beelder/production/core
      dockerfile: build/Dockerfile.api
    image: beelder-api:latest
    container_name: beelder-api
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - beelder-network
      - infra-network
    environment:
      - SERVER_COMMANDS_TOPIC=beelder.server.commands
      - SERVER_PROGRESS_TOPIC=beelder.server.progress
      - GROUP_ID=beelder.api.group
      - BROKER=redpanda:9092

  worker:
    build:
      context: /srv/apps/beelder/production/core
      dockerfile: build/Dockerfile.worker
    image: beelder-worker:latest
    container_name: beelder-worker
    restart: unless-stopped
    networks:
      - beelder-network
      - infra-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONSUMER_TOPIC=beelder.server.commands
      - PRODUCER_TOPIC=beelder.server.progress
      - GROUP_ID=beelder.worker.group
      - DOCKER_HOST=unix:///var/run/docker.sock
      - BUILDER_CONFIG={"max_concurrent_builds":3, "max_alive_servers":5, "timeout_seconds":120}
      - BROKER=redpanda:9092

  app:
    build:
      context: /srv/apps/beelder/production/app
      dockerfile: Dockerfile
    image: beelder-app:latest
    container_name: beelder-app
    ports:
      - "82:80"
    restart: unless-stopped
    networks:
      - beelder-network
    depends_on:
      - api

networks:
  beelder-network:
    driver: bridge
  infra-network:
    name: infra-network
    external: true