services:
  api:
    build:
      context: /srv/apps/beelder/staging/core
      dockerfile: build/Dockerfile.api
    image: beelder-staging-api:latest
    container_name: beelder-staging-api
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - beelder-staging-network
      - infra-network
    environment:
      - SERVER_COMMANDS_TOPIC=beelder.staging.server.commands
      - SERVER_PROGRESS_TOPIC=beelder.staging.server.progress
      - GROUP_ID=beelder.staging.api.group
      - BROKER=redpanda:9092

  worker:
    build:
      context: /srv/apps/beelder/staging/core
      dockerfile: build/Dockerfile.worker
    image: beelder-staging-worker:latest
    container_name: beelder-staging-worker
    restart: unless-stopped
    networks:
      - beelder-staging-network
      - infra-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/apps/beelder/shared/assets:/assets
    environment:
      - CONSUMER_TOPIC=beelder.staging.server.commands
      - PRODUCER_TOPIC=beelder.staging.server.progress
      - GROUP_ID=beelder.staging.worker.group
      - DOCKER_HOST=unix:///var/run/docker.sock
      - BUILDER_CONFIG={"max_concurrent_builds":3, "max_alive_servers":5, "timeout_seconds":120, "assets_path":"/assets"}
      - BROKER=redpanda:9092

  app:
    build:
      context: /srv/apps/beelder/staging/app
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_STAGE=staging
    image: beelder-staging-app:latest
    container_name: beelder-staging-app
    ports:
      - "81:80"
    restart: unless-stopped
    networks:
      - beelder-staging-network
    depends_on:
      - api

networks:
  beelder-staging-network:
    driver: bridge
  infra-network:
    name: infra-network
    external: true